# Improved track config
track: improved
loss_name: conditional  # cross_entropy for exp, focal for icm/te
label_smoothing: 0.0  # for exp
focal_gamma: 2.2  # for icm/te
compute_class_weights_from_train: true
